### ISSUE TITLE
Support for C# Nullable Projects

### ISSUE THREAD

**Issue by johngold-onshift** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#101]
Hello,
We would like to use Scaffolding Handlebars in a Nullable C# project; as such there needs to be a way to add "?" after fields that are nullable. 

To not maintain a fork separately Ideally looking to have a merge of :
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/99

**Comment by tonysneed** [comment]
Sorry I'm behind on this, but plan to look at this and #99 today.
