### ISSUE TITLE
Change namespace of extension method

### ISSUE THREAD

**Issue by ErikEJ** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#11]
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/src/EntityFrameworkCore.Scaffolding.Handlebars/ServiceCollectionExtensions.cs#L5 

To something like: Microsoft.EntityFrameworkCore.Design

**Comment by tonysneed** [comment]
Sure .. is the problem that VS doesn’t provide a quick fix for bringing in extension method namespaces (like ReSharper does)?

**Comment by ErikEJ** [comment]
It is just the design pattern for current extension methods,  and will cause much less friction due to missing namespaces, yes.

**Comment by ErikEJ** [comment]
(VS does provide a quick fix for missing namespaces, but many VS users are not capable of using it)

**Comment by tonysneed** [comment]
No prob .. that’s why it’s in beta. :)

**Comment by tonysneed** [comment]
I'll fix this for the RTM release.

**Comment by tonysneed** [comment]
Resolved by #20.

**Comment by tonysneed** [comment]
Published here: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.0.0-rc3

**Comment by ErikEJ** [comment]
OMG - I can't keep up ! 😄
