### ISSUE TITLE
[QUESTION / DISCUSSION] Multiple Templates

### ISSUE THREAD

**Issue by Illinariss** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#123]
Hi,
two questions.

Question 1.
I have 2 librarys for entities (client and server) and each needs different templates.
At the moment I have to Switch the Templates for each Scaffolding. 
Is there a way to run Scaffolding once and:
-  create models_version_1 with templates_1 in project 1
-  models_2 with templates_2 in project 2 
?
Or anything similar ?

Question 2.
To get the `property.IsKey()` and `property.IsForeignKey()` value i had to extent `HbsCSharpEntityTypeGenerator` and `HbsEntityTypeTransformationService`.

```c#
 properties.Add(new Dictionary<string, object>
                {
                    { "property-type", propertyType },
                    { "property-name", property.Name },
                    { "property-annotations",  PropertyAnnotationsData },
                    { "property-comment", property.GetComment() },
                    { "property-isnullable", property.IsNullable },
                    { "nullable-reference-types", _options?.Value?.EnableNullableReferenceTypes == true },
                    { "property-iskey", property.IsKey() },
                    { "property-isforeignkey", property.IsForeignKey() }
                });
```
```c#
 transformedProperties.Add(new Dictionary<string, object>
                {
                    { "property-type", transformedProp.PropertyType },
                    { "property-name", transformedProp.PropertyName },
                    { "property-annotations", property["property-annotations"] },
                    { "property-comment", property["property-comment"] },
                    { "property-isnullable", transformedProp.PropertyIsNullable },
                    { "nullable-reference-types", property["nullable-reference-types"] },
                    { "property-iskey", property["property-iskey"]},
                    { "property-isforeignkey",property["property-isforeignkey"]}
                });
```
What is the right way to get the property informations ?

**Comment by tonysneed** [comment]
@Illinariss Response to Question 1:
> Is there a way to run Scaffolding once and generate entities for more than one project at the same time? [paraphrased]

Not really. The way the EF Core CLI works is that it is [scoped to just one project](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#using-the-tools), called the "startup project," which must be a .NET Core library or app. You can specify a different "target project," which can be for example a .NET Standard library, but you can only scaffold one project each time you run the `dotnet ef dbcontext scaffold` command.

What you're going to need to do is run the scaffolding command _twice_: once for the client project and again for the server project. Each project will need its own **CodeTemplates** folder where you can customize the code generation in different ways.

**Comment by tonysneed** [comment]
@Illinariss Response to Question 2:

> What is the right way to get the property informations?

You have the right approach. Extend `HbsCSharpEntityTypeGenerator` to override `GenerateProperties`, and extend `HbsEntityTypeTransformationService` to override `TransformProperties`.

Then add these lines of code to your `ScaffoldingDesignTimeServices` class:
```csharp
services.AddSingleton<ICSharpEntityTypeGenerator, MyHbsCSharpEntityTypeGenerator>();
services.AddSingleton<IEntityTypeTransformationService, MyHbsEntityTypeTransformationService>();
```

Alternatively, if you think `property.IsKey` and `property.IsForeignKey` might be useful for others, you can submit a pull request to add these, as well as other common property info properties. If so, be sure to read the project [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md) first.

**Comment by tonysneed** [comment]
Please re-open if I can further clarify or answer any other questions.
