### ISSUE TITLE
[QUESTION / DISCUSSION]

### ISSUE THREAD

**Issue by jryutzy** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#128]
dotnet ef dbcontext scaffold "Server=localhost;Database=Demo;Persist Security Info=False;User ID=sa;Password=removed" Microsoft.EntityFrameworkCore.SqlServer --schema App --output-dir zGenerated_Code_dncli --force                                                    

trying to add customization to templates but getting this error when trying to add anything
![image](https://user-images.githubusercontent.com/67274124/86270551-68bf9d80-bb99-11ea-84cb-c6d4f4c58f47.png)

![image](https://user-images.githubusercontent.com/67274124/86270575-71b06f00-bb99-11ea-9e8b-81feadd4e79a.png)

![image](https://user-images.githubusercontent.com/67274124/86270599-7b39d700-bb99-11ea-8259-febe174fd73a.png)

ideally trying to get this to work
![image](https://user-images.githubusercontent.com/67274124/86270805-d4096f80-bb99-11ea-8d3c-69956cb6fdb2.png)

**Comment by tonysneed** [comment]
Thanks for your question. Support for EF Core 5.x has not yet been added to Handlebars Scaffolding. You need to use a released (non-preview or beta) version of Microsoft.EntityFrameworkCore packages.

**Comment by jryutzy** [comment]
Thanks Tony. Do you know when we might expect it? --no-onconfiguring, --namespace and --context-namespace are a few features in EF 5 I've been using.

**Comment by tonysneed** [comment]
I would like to get this done before the end of July. Tracking the issue with #129.
