### ISSUE TITLE
[Question] How to have an index that could be incremented by hand from inside the main template and partials

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#139]
I would like to add a Newtonsoft.Json attribute **[JsonProperty(Order = X)]** in the c# generated code.
X should start at one and would be incremented for each properties and each navigation properties (thus in each corresponding partial in my case).
Is it something that we could implement? Any guidance to allow me to start with something?
Thanks in advance.

**Comment by tonysneed** [comment]
I think the best way to do this would be to extend `HbsCSharpEntityTypeGenerator` and override `GenerateProperties`. Then you can add `property-order` to the template data and use it in your hbs file.

For an example of this approach see [here](https://github.com/TrackableEntities/ef-core-community-handlebars#7-full-control-extend-handlebars-generators).

**Comment by omatrot** [comment]
Thanks for that.
