### ISSUE TITLE
Add ability to use Handlebars Helper

### ISSUE THREAD

**Issue by SgTS2020** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#14]
Include feature like  : 

- remove first characters  (table name is tblCustomer should be named as class Customer)  
- Fomat string (class name) in CamelCase
...
Such as we can do with Handelbars Helper.

**Comment by tonysneed** [comment]
Resolved by #19. See [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/19#issuecomment-392257554).

**Comment by tonysneed** [comment]
Included with RC3 release.
