### ISSUE TITLE
[Feature] Customize context file name

### ISSUE THREAD

**Issue by Hedi-s** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#141]
**Is your feature request related to a problem? Please describe.**
I am using a script to do few things that couldn't be done by the scaffolding.
I just discovered this project which covers everything except for the context file name.
On my current project the generated files name are like _ContextName.generated.cs_ or _EntityName.generated.cs_.
We can customize entities file name with the `entityFileNameTransformer` but not for the context.

**Describe the solution you'd like**
I would like to add a `contextFileNameTransformer` to handle context file name.

**Comment by tonysneed** [comment]
Good suggestion. I can add the feature. Or let me know if you would like to submit a PR.

**Comment by Hedi-s** [comment]
I will submit a pull request.

**Comment by tonysneed** [comment]
@Hedi-s Released: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v3.8.4

Nuget package now publishing: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/3.8.4
