### ISSUE TITLE
[Bug] Generated code for tables with the same name in multiple schemas is overwritten silently.

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#147]
**Describe the bug**
I have a database with tables with the same name hosted in different database schemas.
The problem is that the class name (thus file name in the end) will be the same, because the schema (or table system id) is not used to produce a unique class name.
Generated files are overwritten silently.

**Expected behavior**
Disctinct class names and no overwritten files on disk.

**To Reproduce**
Scaffold a database that holds 2 tables with the same name in 2 distinct schemas.

**Question**

What do you suggest to be able to generate unique class and file names ?
I'll make a pull request.

**Comment by tonysneed** [comment]
Let me see if I can replicate. There should not be class or file name collisions because they are placed in different namespaces and different file folders.

**Comment by omatrot** [comment]
I forgot to say that I'm using version 2.0.0 of the package code.

**Comment by tonysneed** [comment]
@omatrot You are using version [2.0.0](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/2.0.0) of EntityFrameworkCore.Scaffolding.Handlebars?

Schema folder support was only added with version [3.7.0](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v3.7.0).

I tried this with the latest version and t works as expected, with class files nested within folders that are named after schemas. You just need to enable the option in `ScaffoldingDesignTimeServices`:

```csharp
public class ScaffoldingDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection services)
    {
        services.AddHandlebarsScaffolding(options => options.EnableSchemaFolders = true);
    }
}
```

Interestingly, using the current 5.0 version of dotnet-ef tools, class names for tables in different schemas as are appended with an incrementing integer to make them unique.

**Comment by tonysneed** [comment]
Closing issue, as support for schema folders was added with version 3.7.0.
