### ISSUE TITLE
ExcludedTables no longer includes views with .NET 5 updates

### ISSUE THREAD

**Issue by greggbjensen** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#149]
**Describe the bug**
With the .NET 5 updates, views were no longer being excluded using the ExcludedTables option.

**Expected behavior**
Both views and tables should be matched when excluding with this option.

**To Reproduce**
1. Add a view to the `ModelBuilder` using `ToView()`
2. Add that view name to be excluded by adding it to the `ExcludedTables` list in the options
3. Notice a class is still generated for the view

**Make My Life Easier**
I have created a pull request for this.

**Screenshots**
```csharp
var builder = new ModelBuilder(new ConventionSet());
builder.Entity<Category>()
	.ToView("Category", "dbo");

builder.Entity<Product>()
	.ToView("Product", "prd");

var options = new HandlebarsScaffoldingOptions
{
	ExcludedTables = new List<string> { "dbo.Category", "dbo.Product" }
};

var entityTypes = builder.Model.GetScaffoldEntityTypes(options);
Assert.DoesNotContain(entityTypes, e => e.ClrType.Name == "Category");  // Fails
Assert.Contains(entityTypes, e => e.ClrType.Name == "Product");
```
**Additional context**
The new IModel has a `GetViewName()` and `GetViewSchema()` that must also be checked now.

**Comment by Leosori** [comment]
@tonysneed Do you still look after this repository? Since the pull request has not been answered for nearly two months, I wonder if I should even prepare a pull request for another issue

**Comment by tonysneed** [comment]
So sorry I missed this. Inbox must have swallowed the notice. I'll have a look at the issue and PR ASAP. Thanks for pinging!

**Comment by Leosori** [comment]
glad to hear this is still maintained. My issue was actually #151. The fix should be pretty easy, but I can prepare a PR if you want some help.

**Comment by tonysneed** [comment]
@Leosori I'll have a look at your issue as well.
