### ISSUE TITLE
Update to 2.1-preview1 ?

### ISSUE THREAD

**Issue by ErikEJ** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#15]
Any plans?

**Comment by tonysneed** [comment]
Yes, but this is a big undertaking because the bits reply on classes in the Internal namespace.  So I thought I would hold off until 2.1-rc.  But it's definitely on the radar.  I'll keep this issue open to remind me to update it to 2.1 when the time comes.

**Comment by tonysneed** [comment]
This issue is resolve with [release 1.0.0-rc1](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v1.0.0-rc1).
The NuGet package has also been published: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.0.0-rc
