### ISSUE TITLE
[Bug] Enabling Nullable Reference Types does not make navigation properties nullable

### ISSUE THREAD

**Issue by Leosori** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#151]
**Describe the bug**
If EnableNullableReferenceTypes is set to true, non-collection nav properties that belong to a nullable property are not marked as nullable. This causes Entity Framework to use INNER JOINs instead of OUTER JOINs when generating the SQL query.

Example of the currently generated entity:

```
class Person
{
    public int Id {get; set;}
    public string Name {get; set;}
    public int FirstAddressId {get; set;}
    public int? SecondAddressId {get; set;}

    // nav property
    public virtual Address FirstAddress { get; set; } = default!;
    public virtual Address SecondAddress { get; set; } = default!;
}
```

**Expected behavior**
```
class Person
{
    public int Id {get; set;}
    public string Name {get; set;}
    public int FirstAddressId {get; set;}
    public int? SecondAddressId {get; set;}

    // nav property
    public virtual Address FirstAddress { get; set; } = default!;
    public virtual Address? SecondAddress { get; set; }
}
```

**Additional context**
Property template looks currently like this and uses `property-isnullable`
```
public {{property-type}} {{property-name}} { get; set; }{{#if nullable-reference-types }}{{#unless property-isnullable}} = default!;{{/unless}}{{/if}}
```

Nav properties have this template:
```
{{#if nav-property-collection}}
        public virtual ICollection<{{nav-property-type}}> {{nav-property-name}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{else}}
        public virtual {{nav-property-type}} {{nav-property-name}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{/if}}
```

In order to get it right, the nav property template needs access to `property-isnullable`
```
{{#if nav-property-collection}}
        public virtual ICollection<{{nav-property-type}}> {{nav-property-name}} { get; set; }{{#if nullable-reference-types}} = default!;{{/if}}
{{else}}
        public virtual {{nav-property-type}}{{#if nullable-reference-types}}{{#if property-isnullable}}?{{/if}}{{/if}} {{nav-property-name}} { get; set; }{{#if nullable-reference-types}}{{#unless property-isnullable}} = default!;{{/unless}}{{/if}}
{{/if}}
```
AFAIK should the collection variant stay non-nullable because this is covered by an empty collection.

**Comment by tonysneed** [comment]
I will see if I can replicate this behavior.

**Comment by tonysneed** [comment]
In order to surface a `nav-property-isnullable` template item, we need to determine whether a navigation property is optional, where the foreign key is nullable. I looked at [INavigation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.metadata.inavigation?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.Metadata.INavigation);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=efcore-5.0), but I could not find an extension method that would reveal this.

@bricelam, Can you point us in the right direction?
