### ISSUE TITLE
Removing Keyless Attribute

### ISSUE THREAD

**Issue by jryutzy** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#156]
We have external tables in our Azure SQL DB that are scaffolded in with the DB Context. We can manually create relationships to them using the approach I outlined here to generate relationships so .Include() works to include these External tables and create a join in the LINQ query based on our manually created relationship.
https://github.com/dotnet/efcore/issues/24373
Looks like it's been filed as a bug by EF Core team so I'm hoping Handlebars will let me remove it until they allow the Fluent API to overwrite the Data Annotation.

However, this requires us removing the [Keyless] attribute manually on the generated class. I'd like to use Handlebars to remove this attribute from classes that are in the Ext schema we use for External tables.

How can I prevent this attribute from being applied conditionally.

I can remove it from the context in the Handlebars Helper but it still gets generated on the .cs file for the entity.
![image](https://user-images.githubusercontent.com/67274124/110863861-4d13a780-828f-11eb-96f5-288622519840.png)

**Comment by jryutzy** [comment]
Is there somehow to add helpers like this called **isdefined**?
https://handlebarsjs.com/guide/builtin-helpers.html#if
![image](https://user-images.githubusercontent.com/67274124/111159363-68bccd80-856f-11eb-831a-6756147936ff.png)

I would like to check fi the value of class-annotation is [Keyless] and schema ends with .Ext then don't render the [Keyless] attribute

**Comment by tonysneed** [comment]
Hi @jryutzy, Thanks for your patience. I noticed that the EF Core team has created https://github.com/dotnet/efcore/issues/24369 to address your issue. They also [suggested](https://github.com/dotnet/efcore/issues/24373#issuecomment-803288929) you try setting `entity.Metadata.IsKeyless = false`.

If you would still like to use Handlebars Scaffolding as a workaround, what you need to do is extend `HbsCSharpEntityTypeGenerator` and override `GenerateEntityTypeDataAnnotations` to omit generation of the Keyless attribute. This is an advanced technique, but you can find instruction [here](https://github.com/TrackableEntities/ef-core-community-handlebars/blob/master/README.md#7-full-control-extend-handlebars-generators).

Let me know if you decide to take this approach and need any assistance.

**Comment by tonysneed** [comment]
Please reopen if there are further questions or concerns.
