### ISSUE TITLE
Couldn't add Helper

### ISSUE THREAD

**Issue by TheDarkBoz** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#16]
Hello

Like I said in EF Core power tools  [https://github.com/ErikEJ/SqlCeToolbox/issues/697](url)

> I have a little issue.. I dont know how add a helper I tried to add in Propreties.hbs the following line before then after the call
> 
> Handlebars.registerHelper('ifEquals', function(arg1, arg2, options) {
>     return (arg1 == arg2) ? options.fn(this) : options.inverse(this);
> });
> I have issue :
> 
> HandlebarsDotNet.HandlebarsRuntimeException: Template references a helper that is not registered. Could not find helper '#ifEquals'

Thank you
Best Regards

**Comment by tonysneed** [comment]
My extension relies on Handlebars. Net, so the helper needs to be registered in C#. It might take me a bit of time to investigate, but there should be a hook. Let me get back to you on this. Thanks in advance for your patience. You might also want to check the documentation on Handlebars.Net.

**Comment by tonysneed** [comment]
Resolved by #19. See [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/pull/19#issuecomment-392257554). /cc @TheDarkBoz

**Comment by tonysneed** [comment]
Included with RC3 release.
