### ISSUE TITLE
AddHandlebarsHelpers ignores all but last one Added

### ISSUE THREAD

**Issue by jryutzy** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#162]
When I have multiple Handlebar Helpers it only recognizes the second one
![image](https://user-images.githubusercontent.com/67274124/113934291-93dbbb00-97c3-11eb-855b-3086a597fc76.png)

![image](https://user-images.githubusercontent.com/67274124/113934177-6c84ee00-97c3-11eb-9ae4-379a1630ff02.png)

It throws an error that it can't find the first helper (attributeHelper)
![image](https://user-images.githubusercontent.com/67274124/113934258-87576280-97c3-11eb-8e93-1b0e12d7b6e2.png)

If I remove the second helper (myHelper) then attributeHelper works but of course myHelper can't be used.

Please advise

**Comment by jryutzy** [comment]
@tonysneed I was able to use this approach until the bug is resolved to fix services.AddHandlebarHelpers()
https://github.com/Handlebars-Net/Handlebars.Net#registering-helpers
![image](https://user-images.githubusercontent.com/67274124/114027653-9aab1200-9845-11eb-9ba7-e9383934d117.png)

**Comment by tonysneed** [comment]
@jryutzy Glad you found a workaround. This looks like a good catch. I'll try to replicate as soon as I get a chance.

**Comment by tonysneed** [comment]
@jryutzy `services.AddHandlebarsHelpers` takes a params argument of helpers so that you can pass multiple helpers at the same time. So instead of calling it multiple times, just call it once and pass both of your helpers.

```csharp
services.AddHandlebarsHelpers(attributeHelper, myHelper);
```
