### ISSUE TITLE
[Question] Changing names of navigation properties

### ISSUE THREAD

**Issue by skuami** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#163]
In a project I have a translation table and many other tables with one or more columns to be translated. Those tables are joined through a TranslationKey. 
The TranslationKey has on each table (not the translation table) a unique index. On the translation table is the primary key constructed with the combination of TranslationKey and LanguageCode.

Since the tables are not joined through the primary key - EF will generate "funny" names for the navigation properties.
I posted this question also on [Stackoverflow](https://stackoverflow.com/questions/66786326/ef-core-5-db-first-naming-of-navigation-properties-inverseproperty/66925586#66925586).

I tried to use the navPropertyTransformer. There are to little information in the EntityPropertyInfo to generate a new name for tables with multiple translations.
Apart from that I am having also following issue (not sure if it is a bug or if I am doing something wrong):

The nav property gets renamed correctly but the initialization in the constructor gets not renamed:
![image](https://user-images.githubusercontent.com/13868838/114043446-94895580-9886-11eb-9151-757485dde295.png)

Here's the transformation code I am using:
```
services.AddHandlebarsTransformers(navPropertyTransformer: TransformTranslationKeyNavProperty);

private EntityPropertyInfo TransformTranslationKeyNavProperty(EntityPropertyInfo propertyInfo)
{
        var propName = propertyInfo.PropertyName;
        if (propName.Contains("TranslationKey") && propName != "TranslationKey")
                return new EntityPropertyInfo(propertyInfo.PropertyType, "Translation" + propertyInfo.PropertyType, propertyInfo.PropertyIsNullable);
            
                return propertyInfo;
}
```

**Comment by tonysneed** [comment]
All the transformations need to be done consistently, so that the type names match. For example, see how `"Foo"` is appended  in multiple transformers.

```csharp
services.AddHandlebarsTransformers(
    entityNameTransformer: n => n + "Foo",
    entityFileNameTransformer: n => n + "Foo",
    constructorTransformer: e => new EntityPropertyInfo(e.PropertyType + "Foo", e.PropertyName + "Foo"),
    propertyTransformer: e => new EntityPropertyInfo(e.PropertyType, e.PropertyName + "Foo"),
    navPropertyTransformer: e => new EntityPropertyInfo(e.PropertyType + "Foo", e.PropertyName + "Foo"));
```

**Comment by tonysneed** [comment]
@skuami Did you find my answer helpful? Do you require further assistance with this issue? If not, I will close.

**Comment by skuami** [comment]
@tonysneed Thanks for your answer. I couldn't solve the problem yet. I am dependend on the open PR with additional information for navPropertyTransform. 
I will close this question as soon as I could solve it, ok?

**Comment by skuami** [comment]
@tonysneed As I mentioned on the open PR - the additional NavigationDetail information helping me to solve my problem. I hope the PR can be merged anytime soon. I am using code from the PR for now.
