### ISSUE TITLE
Generate Xaml for basic CRUD 

### ISSUE THREAD

**Issue by ghisbo** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#165]
The handlebars look very well suited for generating the xaml file for wpf.
Very often one wants a very basic CRUD screen where the fields of a database table are set as "Field: "  , textbox binding to FIeld

best regards

**Comment by tonysneed** [comment]
Hi @ghisbo, Appreciate the issue. For generating anything other than C# or TypeScript, I would recommend following the process I outline [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/158#issuecomment-817397952) in this issue. Basically, the ultimate extensibility hook is to extend the generator classes. You should be able to accomplish your objective in this way. Please let me know if you need any further clarification or assistance.

**Comment by ghisbo** [comment]
Thank you for the feedback. I am not so proficient in these ( i am 65 and learning ) .
Does it mean i should clone this "EntityFrameworkCore.Scaffolding.Handlebars" and adapt the coding in there ? 
I am using EF Core power Tools.

**Comment by tonysneed** [comment]
Rather that using Handlebars Scaffolding for this case, I suggest you generate XAML from C# classes. You can use a more general purpose tool, such as [T4](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019). To get started see this [article](https://docs.microsoft.com/en-us/visualstudio/modeling/walkthrough-generating-code-by-using-text-templates?view=vs-2019).

**Comment by tonysneed** [comment]
PS. I would suggest you have a look at the [work](https://github.com/bricelam/EFCore.TextTemplating) Brice Lamb has done with [T4 and EF Core Reverse Engineering](https://www.bricelam.net/2020/02/03/t4-and-efcore.html). T4 is more flexible in some ways than Handlebars, because you can embed code directly in the templates.

**Comment by ghisbo** [comment]
I did look at T4 but the coding is very confusing even with the intellisense help.
 I am looking TryAndErr0r /EntityFrameworkCore.Scaffolding.Handlebars. I find the Handlebars much more user friendly.

**Comment by tonysneed** [comment]
> I find the Handlebars much more user friendly.

Thanks you!
