### ISSUE TITLE
[Bug] AddHandlebarsTransformers entityNameTransformer name is confusing

### ISSUE THREAD

**Issue by JonruAlveus** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#171]
**Describe the bug**
In ServiceCollectionExtensions.AddHandlebarsTransformers, the second parameter (entityNameTransformer) is confusing because it's actually transforming the entity's type name, not the name of the entity itself. I was hoping to use it to transform the generated DbSet name with it, but that's not what it does.

**Expected behavior**
The parameter name/description should be entityTypeNameTransformer, as it is elsewhere (like HbsCSharpDbContextGenerator.GenerateDbSets)

**To Reproduce**
![image](https://user-images.githubusercontent.com/15954362/124606621-fa28b600-de64-11eb-9789-3e9f1c235a40.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/15954362/124606548-e8dfa980-de64-11eb-93da-7176f9ffe462.png)

**Comment by tonysneed** [comment]
Since this is a potentially breaking change, I'll add it to v6, which will be based on EF Core 6.

**Comment by tonysneed** [comment]
Resolved with v6.0.0-preview4.

**Comment by johnwc** [comment]
@tonysneed How would someone go about changing the name of the DbSet property names? Our naming convention is that our views starts with lower case "v", how can we get that to be in the DBSet name as well? It currently capitalizes the V like VTempSensors.
