### ISSUE TITLE
[Question] Is there a way to skip columns

### ISSUE THREAD

**Issue by jgill248** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#172]
I have many tables in the database that have audit columns. Is there a way to use IDesignTimeServices to skip those columns on every table during entity generation?

**Comment by tonysneed** [comment]
This is a situation where you will need to take full control of entity generation by extending  HbsCSharpEntityTypeGenerator and overriding `GenerateProperties`. See [here](https://github.com/TrackableEntities/ef-core-community-handlebars#7-full-control-extend-handlebars-generators) for an example of how to do that.
