### ISSUE TITLE
[Feature] Update to EF Core 6

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#181]
Update to EF Core 6 sometime before EF Core 6 is released.

**Comment by tibitoth** [comment]
@tonysneed EF Core 6 was released :)

**Comment by tonysneed** [comment]
Hi folks, Super sorry I haven’t been able to upgrade for EF Core 6 in time. It will be my top priority this weekend.

Of course, a PR would be gratefully accepted!

**Comment by biesterv** [comment]
Nice work Rich!

**Comment by tonysneed** [comment]
Closed by #190. Thank you Rich!

**Comment by tonysneed** [comment]
Upgrade included with release [v6.0.0-preview1.](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v6.0.0-preview1)

NuGet: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/6.0.0-preview1
