### ISSUE TITLE
[Bug] Cannot use latest release of EntityFramework.Core packages

### ISSUE THREAD

**Issue by RussKahler1970** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#183]
**Describe the bug**
Getting an error trying to create my own version 

**Expected behavior**
Should be able to use latest version of packages. 

**To Reproduce**
Create a .net 5 Asp.net website, use current EntityFramework.Core and Design packages. 
Create type inhert from HbsCSharpEntityTypeGenerator

Get this error 
The type 'CSharpEntityTypeGenerator' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.EntityFrameworkCore.Design, Version=5.0.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by 1legality** [comment]
I am currently having the same problem.

Currently running .NET5 on Visual Studio 2019

Scaffolding.Handlebars versions 5.0.4
EntityFramework 5.0.11

Visual Studio 2019

**Comment by tonysneed** [comment]
Have you tried updating your NuGet packages?

**Comment by tonysneed** [comment]
Closing, as it seems this was resolved.
