### ISSUE TITLE
[Bug] Issue with final text being encoded 

### ISSUE THREAD

**Issue by RussKahler1970** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#184]
I am trying to add a base class which is supporting generics.  
I am getting this 
public partial class MyEntity: EntityBase&lt;int&gt; 

When I want 
public partial class MyEntity: EntityBase<int> 

Any thoughts on how to deal with this?

**Comment by tonysneed** [comment]
I’ll need more context to help. Do you have a sample repo to share?

**Comment by RussKahler1970** [comment]
Sorry I had it backwards above.  

I want public partial class MyEntity: EntityBase<int>

but I don't know how to add in the class template to get the generics to work.

**Comment by tonysneed** [comment]
This is a dup of #30. We are waiting for a fix from Handlebars to merge the fix #180. I’ll ping them to check on progress.

**Comment by tonysneed** [comment]
Closing as a duplicate of #30. Waiting for Handlebars.Net to fix this [issue](https://github.com/Handlebars-Net/Handlebars.Net/issues/468).

**Comment by tonysneed** [comment]
Re-opening to see if [fix](https://github.com/Handlebars-Net/Handlebars.Net/pull/473) to Handlebars.Net would address this as well.
