### ISSUE TITLE
[Feature] Make IContextTransformationService available when using Handlebars transformers 

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#198]
Add `IContextTransformationService` to `HbsCSharpDbContextGenerator` so that the context can be made available when
using the other transforms:
```csharp
entityNameTransformer: MapEntityName,
constructorTransformer: MapPropertyInfo,
propertyTransformer: MapPropertyInfo,
navPropertyTransformer: MapNavPropertyInfo,
entityFileNameTransformer: MapEntityName
```

**Comment by tonysneed** [comment]
Transfer https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/188#issuecomment-994884840 to this issue.

**Comment by tonysneed** [comment]
@gpender I am trying to wrap my head around why you need to call `ContextTransformationService.TransformContextFileName` in the `WriteCode` method of `HbsCSharpDbContextGenerator` and how this would enable you to access the transformed context file name in your transformer class.

Perhaps you would be kind enough to create a small repo containing an example transformer class that shows how calling `ContextTransformationService.TransformContextFileName` in `HbsCSharpDbContextGenerator` surfaces the context file name so that you can use it in your other transform methods?

**Comment by gpender** [comment]
Hi @tonysneed and Happy New Year :)
sorry for not getting back to you sooner. 
In our Use Case application we have multiple existing SQLSERVER databases which we are migrating and there are tables with duplicate names.

So for example we have the table Aircraft appearing in 2 databases (The Aircraft tables are both different) 
DatabaseA with table Aircraft
DatabaseB with table Aircraft

To scaffold the entities correctly I would like to have a single mappings.json lookup file where we have all the mappings for all databases:-
```
[
	{
		"Name": "DatabaseA:Aircraft",
		"NameOverride": "CivilianAircraft",
		"Mappings": [
			{
				"Name": "Tail",
				"NameMapping": "TailLivery"
			}
		]
	},
	{
		"Name": "DatabaseB:Aircraft",
		"Mappings": [
			{
				"Name": "Type",
				"NameMapping": "AircraftType"
			}
		]
	}
]
```
My transformer class uses this single json file to make the transforms and needs the current context (database) to fully qualify the entries.

In the code below you can see that I store the _context locally when it is called and then use it to access the entries in the mappings.json file.
I hope this makes sense :) 
```
namespace HandlebarsScaffolding
{
	public class ScaffoldingDesignTimeServices : IDesignTimeServices
	{
		private string _entityName, _context;
		private readonly EntityMappings _mappings;
		public ScaffoldingDesignTimeServices()
		{
			try
			{
                _mappings = File.ReadAllText($@"{Environment.CurrentDirectory}\Mapping\mappings.json").FromJson<EntityMappings>();
                Console.WriteLine($@"Reading {Environment.CurrentDirectory}\Mapping\mappings.json");
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				throw;
			}
		}
		public void ConfigureDesignTimeServices(IServiceCollection services)
		{
			services.AddHandlebarsScaffolding(options);
			services.AddHandlebarsTransformers(

				contextFileNameTransformer: (c) =>
				{
					_context = Path.GetFileNameWithoutExtension(c);
					return c;
				},
				entityNameTransformer: MapEntityName,
				constructorTransformer: MapPropertyInfo,
				propertyTransformer: MapPropertyInfo,
				navPropertyTransformer: MapNavPropertyInfo,
				entityFileNameTransformer: MapEntityName);
		}
		private string MapEntityName(string entityName)
		{
			_entityName = entityName;
			var nameOverride = _mappings.FirstOrDefault(e => e.Name == $"{_context}:{_entityName}")?.NameOverride;
			return nameOverride ?? entityName;
		}
		private EntityPropertyInfo MapNavPropertyInfo(EntityPropertyInfo e)
		{
			return new EntityPropertyInfo(MapPropertyTypeName(e.PropertyType), MapPropertyName(e.PropertyName, false));
		}
		private EntityPropertyInfo MapPropertyInfo(EntityPropertyInfo e)
		{
			return new EntityPropertyInfo(MapPropertyTypeName(e.PropertyType), MapPropertyName(e.PropertyName));
		}
		private string MapPropertyTypeName(string propertyTypeName)
		{
			var propertyTypeNameOverride = _mappings.FirstOrDefault(e => e.Name == $"{_context}:{propertyTypeName}")?.NameOverride;
			return propertyTypeNameOverride ?? propertyTypeName;
		}
		private string MapPropertyName(string propertyName, bool useEntityNameFilter = true)
		{
			IEnumerable<Mapping> entityMappings = null;
			if (useEntityNameFilter)
				entityMappings = _mappings.Where(m => m.Name == $"{_context}:{_entityName}").SelectMany(m => m.Mappings);
			else
				entityMappings = _mappings.Where(m=>m.Name.Split(':')[0] == _context).SelectMany(m => m.Mappings);
			var map = entityMappings.FirstOrDefault(m => m.Name == propertyName);
			return map != null ? map.NameMapping : propertyName;
		}
	}
}

```

**Comment by gpender** [comment]
Hi @tonysneed 

I guess you are very busy at the moment, teaching ? You're repos are always an interesting read :)
Are you likely to be releasing a new version of the Handlebars Scaffolding soon?
The first PR I submitted that you have already signed off on would be very useful to us in the next month or so but I understand if you are busy

Kind Regards
Guy

**Comment by tonysneed** [comment]
Been super busy, but I haven’t forgotten about this. Thanks for patience and please stay tuned.
