### ISSUE TITLE
HasKey Reference Left Out with Non-Conventional Key Property

### ISSUE THREAD

**Issue by davidhendrickmb** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#203]
Hi there,

This is in relation to the issue here which Erik has mentioned is a problem with this package.
The HasKey reference is being left out when I use Handlebars templates with EF Core 6. Would you know of a fix for this?https://github.com/ErikEJ/EFCorePowerTools/issues/1250

Thanks,
David

**Comment by ErikEJ** [comment]
Or maybe the Key attribute?

**Comment by tonysneed** [comment]
Thanks for reporting the bug. I'll work on fixing it.

**Comment by davidhendrickmb** [comment]
Thank you :)
If you happen to find a temporary workaround please let me know as I'm trying to test out Net 6 upgrade.

**Comment by tonysneed** [comment]
@davidhendrickmb I am looking at this now. It has to do with the PK not following EF Core naming conventions. I will fix the bug, but if you wish to have a workaround, simply make sure your PK entity property follows the standard [EF Core naming convention for key fields](https://docs.microsoft.com/en-us/ef/core/modeling/keys). In other words, entitynameId. In your case this would be: `AccompanimentTypeId`

**Comment by ErikEJ** [comment]
Potential duplicate: https://github.com/ErikEJ/EFCorePowerTools/issues/1256

**Comment by RaulFunezp** [comment]
I have exactly the same problem when using HandleBars in ErikEJ/EfCorePowerTools. The name of my HasKey not generated is like this: AeDeCtaCB.

I hope that when Tony solves that bug, it will solve my case too.
Thank you

**Comment by tonysneed** [comment]
@ErikEJ @davidhendrickmb @RaulFunezp Fixed with Handlebars [v6.0.3](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/6.0.3).

**Comment by davidhendrickmb** [comment]
Thanks Tony, much appreciated!
