### ISSUE TITLE
Handlebar Support for Stored Procedure Generation

### ISSUE THREAD

**Issue by bmainsteleo** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#206]
It doesn't appear that there is support for Stored Procedures with the Handlebar generation process?  It would be great if that could be included, both as the methods within the Context, and for the entities that represent the SP results.

**Comment by ErikEJ** [comment]
Handlebars uses what EF Core generates and there is no support for this in EF Core.

EF Core Power Tools reverse engineers both stored procedures and functions.

**Comment by bmainsteleo** [comment]
OK thanks for the update.  As an enhancement request: could EF Core Power Tools add handlebar support to do this?

**Comment by tonysneed** [comment]
I haven’t planned to add this feature to Handlebars, as it only uses EF Core scaffolding, which does it reverse engineer entities from sprocs.

**Comment by ErikEJ** [comment]
You mean not?

**Comment by tonysneed** [comment]
Thanks — corrected.

**Comment by ErikEJ** [comment]
@bmainsteleo please create a feature request in the EF Core Power Tools repo
