### ISSUE TITLE
Generate seporate IEntityTypeConfiguration classes (avoids large OnModelCreating) like EFCore Powertool 

### ISSUE THREAD

**Issue by csandun** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#211]
I am a big fan of ErikEJ's EFCore power tool. But our use cases in reverse engineering, we have a few edge cases that cannot resolve using the EFCore power tool. By the way, I decided to implement my code to generate using Handlebars. That way, I faced issues in developing separate  IEntityTypeConfiguration classes using the Scaffold command. 

Have you any idea do that requirement using handlebars? And Scaffolding command?

Thanks

**Comment by tony-asu** [comment]
Any update on this?  any idea if it's feasible?

**Comment by tonysneed** [comment]
Scaffolding `IEntityTypeConfiguration` classes is not currently supported by the Handlebars library.

**Comment by tony-asu** [comment]
Is there an example of using both T4 and handlebar templates?  I've been using the handlebar templates for a while and there's alot to move to t4's
