### ISSUE TITLE
[Question] DbContext public parameterless ctor added in #220

### ISSUE THREAD

**Issue by aaron-kruse** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#221]
#220 added a public parameterless constructor to the DbContext constructor templates:
https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/2ddd977384a6781ed24f490f00a9f625fcd59c3d/src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/Partials/DbConstructor.hbs#L1-L3

I looked around for information on why this was added but couldn't find anything about this in particular. The reason I ask is because I'm not sure I want to add this to our templates since it seems like it could be problematic (ex. services wouldn't get injected via DI, no base call, etc.) but I'm also not sure I want to exclude something that was specifically added in this update without knowing why it was added and what impact removing it might have.

Thanks for any feedback and all your hard work!

**Comment by ErikEJ** [comment]
FWIW, the default .NET 7 reverse engineering does not include the constructor either.

**Comment by tonysneed** [comment]
I just tried this, and can see that the DbContext generated by the default tooling includes two constructors, one of which is parameterless.

the reason I added it to the hbs partial template was to bring it into conformity with the default tooling. Having it does not interfere with DI.

**Comment by ErikEJ** [comment]
Is that the EF Core 7 tooling - I do not see that

**Comment by tonysneed** [comment]
> Is that the EF Core 7 tooling - I do not see that

I created a repo [here](https://github.com/tonysneed/ef-core-7-scaffolding-test) to test the default scaffolding behavior.

This is what I got unning the default command:

```csharp
public partial class NorthwindSlimContext : DbContext
{
    public NorthwindSlimContext()
    {
    }

    public NorthwindSlimContext(DbContextOptions<NorthwindSlimContext> options)
        : base(options)
    {
    }
```

This is how the tooling has behaved for quite some time. My hbs templates excluded the parameterless ctor, but I thought it would be a good idea to bring it more in alignment with the default tooling output.

**Comment by ErikEJ** [comment]
Interesting. Let me double check in EF Core Power Tools

**Comment by ErikEJ** [comment]
@tonysneed My bad - EF Core 7 tooling includes the constructor for sure!

**Comment by aaron-kruse** [comment]
Thank you both for the quick feedback and looking into this! After seeing your responses, I looked into this a little bit more and from what I was seeing, it sounded like earlier versions of .NET Core originally weren't generating a parameterless constructor for the DbContext class, but that would lead to problems later when trying to scaffold out controllers/views (resulting in a "No parameterless constructor defined for this object" error).

This being the case, things make a little more sense now. The default tooling added this in at some point presumably to address issues with scaffolding controllers/views, and it's been added to the Handlebars templates to reflect this change (which makes perfect sense). This also makes me feel a little better about excluding it from our template/DbContext class to avoid problems in the future since we don't scaffold controllers/views anyways.

Thanks again for everything you guys do!

**Comment by tonysneed** [comment]
@aaron-kruse Glad I could answer your question and that the solution works for you. The beauty of the template is that you can always modify to suit your needs. 😀
