### ISSUE TITLE
EF Core Power Tools

### ISSUE THREAD

**Issue by ignaciosalazarcalle** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#224]
Hello,

I don't fully understand the functionality of how to make custom templates work.

I have a project with Context from the data model and I am using EF Core Power Tool to generate the entities and context from a database.

I would like that, when the entities are generated, I can perform a validation in my template so that, depending on the name of the table, it inherits the class of an entity of its own.

Is this possible?

I am working with EF Core 6

Regards,

**Comment by tonysneed** [comment]
It is not possible to insert code into the templates. If you would like this behavior, try the [T4 approach](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli) supported by EF 7.
