### ISSUE TITLE
Could not load type Microsoft.EntityFrameworkCore.Scaffolding.Internal.ICSharpDbContextGenerator

### ISSUE THREAD

**Issue by mwmccallum** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#225]
Updating EF Core 6 to 7 in a .NetCore 6 project. Running Scaffold Command results in error:

Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.ICSharpDbContextGenerator' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=7.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I have seen references saying that Microsoft.EntityFrameworkCore.Scaffolding.Internal does not exist in EF Core 7. 

This is where the error is thrown:
at Microsoft.EntityFrameworkCore.Design.ServiceCollectionExtensions.AddHandlebarsScaffolding(IServiceCollection services, Action`1 configureOptions)

This is the setup I am using:

`  public void ConfigureDesignTimeServices ( IServiceCollection services )
  {
    GetTableNameChanges ();

    services.AddHandlebarsScaffolding ( options =>
    {
      options.ExcludedTables = GetExcludedTables ();
      options.EnableSchemaFolders = true;
      options.GenerateComments = true;
      Debug.WriteLine ( options.ExcludedTables );
    } );

    // Adds the Variable Transfers from their individual methods defined below
    services.AddHandlebarsTransformers2 (
        entityTypeNameTransformer: this.ReplaceEntityNames,
        entityFileNameTransformer: this.ReplaceEntityNames,
        constructorTransformer: this.ConstructorTransformer,
        propertyTransformer: this.PropertyTransformer,
        navPropertyTransformer: this.NavigationTransformer,
        contextFileNameTransformer: this.ReplaceContextNames
        );

  }`

I believe I have followed your notes for updating from EF Core6 -> 7.

Step 2 refers to updateing to NuGet packages 7.0.0 or later, including EntityFrameworkCore.Scaffolding.Handlebars. However, I only see v6.0.3 for EntityFrameworkCore.Scaffolding.Handlebars.

Thanks, Mike

**Comment by ErikEJ** [comment]
@mwmccallum share your .csproj pls

**Comment by JimWilcox3** [comment]
I am having the same problem.  My project is as follows:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Scaffolding.Handlebars" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.1" />
  </ItemGroup>

</Project>

The only class I have is as follows:

using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;

namespace FAMData
{
    public class ScaffoldingDesignTimeServices : IDesignTimeServices
    {
        public void ConfigureDesignTimeServices(IServiceCollection services)
        {
            services.AddHandlebarsScaffolding();
        }
    }
}

In the Package Manager Console, I am running:

dotnet ef dbcontext scaffold "Server=myserver;Database=mydb;Trusted_Connection=True;Trust Server Certificate=true" Microsoft.EntityFrameworkCore.SqlServer -o Entities -f

This is the entire project.  Am I missing something?

Thanks,
Jim

**Comment by tonysneed** [comment]
Upgrade to EntityFrameworkCore.Scaffolding.Handlebars version [7.0.0-beta1](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/7.0.0-beta1).

I will soon update the package to a stable version.
