### ISSUE TITLE
[Question] Support for EF Core 7?

### ISSUE THREAD

**Issue by slymuffhugger** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#228]
Is there a way to use this package with entity framework 7? I'm getting an error 

Could not load type 'Microsoft.EntityFrameworkCore.Scaffolding.Internal.ICSharpDbContextGenerator'

**Comment by ErikEJ** [comment]
Yes: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/7.0.0-beta1
