### ISSUE TITLE
[Feature] EF Core 8 plans? 

### ISSUE THREAD

**Issue by ErikEJ** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#234]
Any plans to add support for EF Core 8?

**Comment by tejasvih** [comment]
Even we are stuck. Existing version fails with upgraded .net 8 EF Core.

**Comment by tejasvih** [comment]
Thank you!


Regards
Tejasvi
________________________________

**Comment by tejasvih** [comment]
Let me know if I can help in anyway


Regards
Tejasvi
________________________________

**Comment by tonysneed** [comment]
@ErikEJ I've completed the EF 8 upgrade and published v8.0.0-beta1 of the package: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v8.0.0-beta1

**Comment by tejasvih** [comment]
👏


Regards
Tejasvi
________________________________
