### ISSUE TITLE
[Bug] Missing Scaffolded Properties in EF Core 8 and EntityFrameworkCore.Scaffolding.Handlebars (8.0.0-beta1)

### ISSUE THREAD

**Issue by ashwth** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#236]
**Describe the bug**
When using with EF Core 8, properties such as HasDefaultValueSql, HasComputedColumnSql, and HasColumnName are not being generated. This issue arises after upgrading to the EF Core 8 and EntityFrameworkCore.Scaffolding.Handlebars beta package (8.0.0-beta1). In previous versions these properties were generated as expected.

**Expected behavior**
All relevant configurations like HasDefaultValueSql, HasComputedColumnSql, and HasColumnName should be correctly generated as they were in previous versions.

**To Reproduce**
Upgrade an existing project/ Create new to use EF Core 8 and EntityFrameworkCore.Scaffolding.Handlebars  (8.0.0-beta1).
Run the scaffolding process to generate.
Observe that properties such as HasDefaultValueSql, HasComputedColumnSql, and HasColumnName are missing in the scaffolded output.

**Additional context**
Im using Npgsql.EntityFrameworkCore.PostgreSQL.
I tried with default scaffolding without Handlebars these three are generated

**Comment by mwmccallum** [comment]
Found issue that causes this, was in HbsCSharpDbContextGenerator.GenerateProperty where following code was removed from procedure in Commit: 3a35b179a6a5c3dc9035bd3eef4349d6654fcbd5. Upgrade to .NET 8.0 Commit. This is where all the remaining annotations were appended.

`            lines.AddRange(
                AnnotationCodeGenerator.GenerateFluentApiCalls(property, annotations).Select(m => CSharpHelper.Fragment(m))
                    .Concat(GenerateAnnotations(annotations.Values)));
`

**Comment by mwmccallum** [comment]
Adding the above correction into that for #238
