### ISSUE TITLE
Allow setting new value for HasDefaultValue

### ISSUE THREAD

**Issue by johnwc** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#244]
For v8, can you add a `DefaultValue` to `EntityPropertyInfo` that allows us to replace the default value? This would help when setting the type as an Enum, and ef is setting it as a number. Which throws an error. `HasDefaultValue(0)` vs `HasDefaultValue(MyEnum.Default)`

**Comment by johnwc** [comment]
@tonysneed should of asked if we could add a property to allow us to set the `HasSentinel` value as well. How can we get that added as well so EF does not throw warnings upon context load about this?

**Comment by tonysneed** [comment]
I don’t see a problem with adding this.
