### ISSUE TITLE
[Feature] Update to .NET 9

### ISSUE THREAD

**Issue by MaxIliashenko** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#246]
**Is your feature request related to a problem? Please describe.**
Please update your project to support EF Core 9

**Additional context**
After updating to .NET 9 and EF Core 9 we got this error
```
Method not found: 'Void Microsoft.EntityFrameworkCore.Scaffolding.ScaffoldedFile..ctor()'.
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
```

**Comment by jryutzy** [comment]
I'm having the same issue. Any ETA when NET 9 will be supported?

**Comment by tonysneed** [comment]
Now that .NET 9 is RTM we will update it to .NET 9.

**Comment by jryutzy** [comment]
> Now that .NET 9 is RTM we will update it to .NET 9.

Thanks Tony! This is a great resource you developed for the NET Community!

**Comment by tonysneed** [comment]
I [released](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/releases/tag/v9.0.0-beta1) [v9.0.0-beta1](https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/9.0.0-beta1) of the library.

@jryutzy @MaxIliashenko Would you please try it out?

**Comment by MaxIliashenko** [comment]
Tested. Works like a charm! Thank you!!!!

**Comment by jryutzy** [comment]
tested and works for me as well..thank you!
