### ISSUE TITLE
AddHandlebarsHelpers not working

### ISSUE THREAD

**Issue by ufetahu** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#31]
I've been trying to generate comments using helpers but it's not working (unlike comments added in .hbs like //comment). Its almost like if the Helper method is not being called. Also, if there is way to check the property name within i.e.:
 if(parameter == "CreatedOn"){
    writer.write("//")
}
Using 
   <TargetFramework>netcoreapp2.1</TargetFramework>

**Comment by ufetahu** [comment]
Hi Anthony,

Thank you for your reply. Attached you will find the ScaffoldingDesignTimeService.cs, DBContext.hbs and the results received from scaffolding in ChronDbContext.cs.

As far as my second question I was thinking whether it’s possible to check the property name within the helper itself, such as:


        void MyHbsHelper(TextWriter writer, object context, object[] parameters)
        {
            foreach (var property in parameters)
            {
                if(property.ToString() == "CreatedBy")
                    writer.Write("//");
            }
        }

 And in .hbs file

{{spaces 8}}{{my-helper}}public {{property-type}} {{property-name}} { get; set; }


I appreciate you taking your time.

Regards,

Uran

**Comment by Vizehase** [comment]
I can confirm that issue. I had the same problem when trying to include my own helpers. The method AddHandlebarsHelpers does not seem to find the internal collection in order to append the given helper to it. I succeeded by installing the helpers altogether myself by
`            // Register Handlebars helper
            services.AddHandlebarsHelpers(myHelper); // does not work but the following
            services.AddSingleton(
                provider => (IHbsHelperService)
                    new HbsHelperService(
                        new Dictionary<string, Action<TextWriter, object, object[]>>
                        {
                            {
                                "spaces",
                                HandlebarsHelpers.SpacesHelper
                            },
                            {
                                "MyHelper",
                                MyHelper
                            }
                        }));
`

**Comment by tonysneed** [comment]
@ufetahu @Vizehase @IulianParaian This has been fixed in v1.7.0.
