### ISSUE TITLE
[Feature] Customize Classnames

### ISSUE THREAD

**Issue by vertonghenb** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#35]
In some cases the database tables are prefixed with something like "tbl" it would be nice to remove this kind of prefixed in the classname of the generated entities.

**Comment by tonysneed** [comment]
@vertonghenb We are working on a solution to this in #34.

**Comment by tonysneed** [comment]
Resolved by #47 and released in v1.7.0.  Enjoy!
