### ISSUE TITLE
Need version for EF Core 2.2

### ISSUE THREAD

**Issue by ErikEJ** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#39]
Hi, I am updating EF Core Power Tools for EF Core 2.2 - are you able to provide a 2.2 version (I have had to disable this for now)

**Comment by tonysneed** [comment]
Happy to update to 2.2.

**Comment by tonysneed** [comment]
Resolved by #40. Thanks @ErikEJ!

**Comment by ErikEJ** [comment]
Great - has it been published?

**Comment by tonysneed** [comment]
Just published! https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.6.0

**Comment by ErikEJ** [comment]
Now included in latest daily for EF Core 2.2 reverse engineering - thanks!
