### ISSUE TITLE
a couple of questions?

### ISSUE THREAD

**Issue by rothariger** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#56]
hi,

first and simple, is there any way of debugging this? i couldn't find any way... :(

second, i want to create views and webapis, for simple crud pages, could i use this for that purpose?

regards.

**Comment by tonysneed** [comment]
In your IDesignTimeServices implementation, simple add Debugger.Launch(). With ReSharoer you can then decompile and step right into the source code. Or you can use their free dotPeek tool, or simply clone the repo and reference the source code directly.
