### ISSUE TITLE
Doesn't seem to work with .NET Standard

### ISSUE THREAD

**Issue by Alfetta159** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#59]
And I realize that the instructions say to create a .NET Core dll, but I prefer .NET Standard if my assembly isn't a .NET Core web app. I typically have an API (.NET Core) project and a Data (.NET Standard) project and if I need scaffolding or data migrations, I just point to the API project as the start up. So this is more of a feature request. Or am I doing something wrong?

**Comment by tonysneed** [comment]
.NET Core is required by the EF CLI you use on the command line. You can use .NET Standard if you use the EF Core Power Tools, but that doesn’t support some features of my scaffolding tools, such as Handlebars Helpers. For those you need to use the EF Core CLI and then just change the project type afterwards to .NET Standard, which is less than ideal.

**Comment by Alfetta159** [comment]
I don't use EF Core Power Tools, and I use the EF Core CLI all the time to scaffold existing dbs and generate migrations from code in .NET Standard projects. I agree the .NET Core is required, and that's what I meant by setting the start up to another project to one that is a .NET Core dll/app. Again, I don't mean to say this is a bug, it would just be nice. I've decided to go w/ an approach that doesn't require a db first library.

**Comment by tonysneed** [comment]
.NET Core is a requirement of the EF Core CLI, not my library. So there is nothing I can do about it.
