### ISSUE TITLE
Generated entities extends ObservableEntity instead of TrackableEntity

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#66]
Unless there is an option to specify that I'm unaware off, the TypeScript template generates entities that extends ObservableEntity.

Shouldn't it generate entities extending TrackableEntity?

**Comment by tonysneed** [comment]
Are you using [TrackableEntities.Core.Templates.TypeScript](https://github.com/TrackableEntities/TrackableEntities.Core.Templates.TypeScript) (and not [ObservableEntities.Core.Templates.TypeScript](ObservableEntities.Core.Templates.TypeScript))?

```
dotnet new -i TrackableEntities.Core.Templates.TypeScript
dotnet new te-templates-typescript
```

The generated entities should extend `TrackableEntity`.

```csharp
import { TrackableEntity } from 'trackable-entities';
import { Product } from './Product';

export class Category extends TrackableEntity {

  categoryId: number;
  categoryName: string;
  product: Product[];

  constructor() {
    super();
    return super.proxify(this);
  }
}
```

**Comment by omatrot** [comment]
Sorry, you're right, I used dotnet new oe-template-typescript.
