### ISSUE TITLE
[Guidance] HandleBars Block Helper?

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#70]
I'm trying to write a [HandleBars Block Helper](https://github.com/rexm/Handlebars.Net#registering-block-helpers). This seems not supported.

To be more precise, I would like something like [this helper](https://stackoverflow.com/a/47134327/15186).

**Comment by tonysneed** [comment]
Have you tried registering `HandlebarsBlockHelper`? You may need to upgrade Handlebars.Net to the latest package version.

**Comment by omatrot** [comment]
I would have to add code to your project to Alter ServiceCollectionExtensions to add a new method.

But, because [Murphy's law](https://en.wikipedia.org/wiki/Murphy%27s_law) is against me all the time, I can't get your solution to load properly in Visual Studio 2017. Net Standard 2.0 is not available in the project target. However creating a new project from scratch works like a charm...

I had enough for the day. See you tomorrow.

**Comment by tonysneed** [comment]
You should use Visual Studio 2019 and install the .NET Core 2.2 SDK.

Feel free to fork my sample repo, then create a new branch. You will then be able to publish the branch and create a pull request. :)
