### ISSUE TITLE
[Feature request] Allow new partial templates to be registered

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#73]
I naïvely added a new template in the partials folder of my project and tried to called it from the Class template.
I receive the following error at runtime:
>Referenced partial name _partial_name_ could not be resolved

**Comment by tonysneed** [comment]
`SharpTemplateLanguageService` and `TypeScriptTemplateLanguageService` classes would need to be updated to pick up all files in `DbContextPartialsDirectory` and `EntityTypePartialsDirectory`.

Care to submit a pull request? 😄

**Comment by omatrot** [comment]
I'll do that tomorrow morning my time.

**Comment by tonysneed** [comment]
@omatrot Is this resolved?

**Comment by omatrot** [comment]
No coul'nt find the time to look at it.

**Comment by TryAndErr0r** [comment]
I made a fork wich provide this feature. I am new to github so here is the link i guess?https://github.com/TryAndErr0r/EntityFrameworkCore.Scaffolding.Handlebars/tree/aa2b4a90e0bce7cdedfe1b8c4ed0119ed6ec01bb

It is just a few changes. The idea is that all files in the "Partials" folder can be addressed in the DbContext.hbs and Class.hbs file. If the file name is "Propertiesitem.hbs" it can be called with 
`{{{> propertiesitem}}}`

**Comment by gejotas** [comment]
> I made a fork wich provide this feature. I am new to github so here is the link i guess?https://github.com/TryAndErr0r/EntityFrameworkCore.Scaffolding.Handlebars/tree/aa2b4a90e0bce7cdedfe1b8c4ed0119ed6ec01bb
> 
> It is just a few changes. The idea is that all files in the "Partials" folder can be addressed in the DbContext.hbs and Class.hbs file. If the file name is "Propertiesitem.hbs" it can be called with
> `{{{> propertiesitem}}}`

I've created a PR containing your code and some improvements.

**Comment by tonysneed** [comment]
@gejotas I looked for your PR and didn't see it. Can you link to it?

**Comment by gejotas** [comment]
@tonysneed #106
