### ISSUE TITLE
[Feature request] Have a way to know that a property is part of the object identifier (PK)

### ISSUE THREAD

**Issue by omatrot** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#76]
During TypeScript entities generation, I need to know if a property is part of the object identifier. 

I need to tell [serializr](https://github.com/mobxjs/serializr#propschema) by specifiying:
> identifier(): Serialize a field as primitive value, use it as identifier when serializing references (see reference)

Each navigation property is already always a reference.

It seems that this information may be available during csharp entities generation.

I'll be happy to make a pull request for that feature.
Any further guidance would be very welcome.

**Comment by omatrot** [comment]
The object identifier is the combination of the column(s) of the primary key.
The type and/or name are not enough.

**Comment by tonysneed** [comment]
It is in this type of situation that the extensibility of the framework really shines. What you need to do is create a class that inheritance from HbsTypeScriptEntityTypeGenerator,  Then add an is-object-identifier to the data that is surfaced to the handlebars template.

**Comment by omatrot** [comment]
I see that I can create a class that inherits HbsTypeScriptEntityTypeGenerator but I can't see how it will be used instead of the base class. There must be some method to call in ConfigureDesignTimeServices ?

**Comment by tonysneed** [comment]
What you'll need to do is register `MyHbsTypeScriptEntityTypeGenerator` in `ScaffoldingDesignTimeServices`, after calling `services.AddHandlebarsScaffolding`, like so:

```csharp
services.AddSingleton<ICSharpEntityTypeGenerator, MyHbsTypeScriptEntityTypeGenerator>();
```

**Comment by omatrot** [comment]
The code runs but now I have my properties with c# types instead of TypeScript types :|

**Comment by tonysneed** [comment]
You need to use `TypeScriptHelper`. Copy code from `HbsTypeScriptEntityTypeGenerator`.
