### ISSUE TITLE
Entity Name in Plural Form

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#8]
Hi Tony,

Greetings again.

Is there any way you can help us to create entities without pluralization? We prefer Customer instead of Customers.

**Comment by tonysneed** [comment]
So there are a few steps to follow to use pluralization in EF Core.
- Install-Package Inflector
- Add a class that implements `IPluralizer`

```csharp
public class MyPluralizer : IPluralizer
{
    public string Pluralize(string name)
    {
        return Inflector.Inflector.Pluralize(name) ?? name;
    }

    public string Singularize(string name)
    {
        return Inflector.Inflector.Singularize(name) ?? name;
    }
}
```

- Add a line of code to `IDesignTimeServices.ConfigureDesignTimeServices`:

```csharp
services.AddSingleton<IPluralizer, MyPluralizer>();
```

See here for more info: https://docs.microsoft.com/en-us/ef/core/what-is-new/
