### ISSUE TITLE
DbContext is generated without transformed entity names in OnModelCreating

### ISSUE THREAD

**Issue by dmayhak** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#89]
First of all, thanks for an awesome tool! I have however found a small issue:

Adding an entityNameTransformer to the services transformers applies the transformed name everywhere EXCEPT for the modelBuilder.Entity<EntityType>(...) lines in OnModelCreating.

Fix can be applied in HbsCSharpDbContextGenerator.cs in the InitializeEntityTypeBuilder() function:

```
private void InitializeEntityTypeBuilder(IEntityType entityType, IndentedStringBuilder sb)
        {
            if (!_entityTypeBuilderInitialized)
            {
                var transformedEntityName = EntityTypeTransformationService.TransformEntityName(entityType.Name);

                sb.AppendLine();
                sb.AppendLine($"modelBuilder.Entity<{transformedEntityName}>({EntityLambdaIdentifier} =>");
                sb.Append("{");
            }

            _entityTypeBuilderInitialized = true;
        }
```

I am creating a PR for this change. Thanks!

**Comment by tonysneed** [comment]
Fixed by #90.
