### ISSUE TITLE
Need strongly signed dll

### ISSUE THREAD

**Issue by ErikEJ** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#9]
In order for me to provide this with EF Core Power Tools, as Visual Studio extension, I need a strongly signed assembly - both of this and HandleBars.NET. Are you able to provide that (prefer not to include the source directly)

**Comment by tonysneed** [comment]
I don't mind signing my assembly.  I'll have to see if [Handlebars.Net](https://github.com/rexm/Handlebars.Net) is game.

Out of curiosity, why are you signing your assembly?  I've [read](https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/) it's not really done very much these days.

**Comment by ErikEJ** [comment]
Visual Studio refuses to load non-signed assemblies - only other option is to include source...

**Comment by tonysneed** [comment]
Makes sense .. I didn't notice because Trackable Entities is strongly named, so the VSIX didn't complain.

**Comment by tonysneed** [comment]
@ErikEJ Here is my fork of Handlebars.Net that I signed: https://www.nuget.org/packages/Handlebars.Net.Signed

Next is signing my project ...

**Comment by tonysneed** [comment]
Resolved by #18. Published to NuGet: https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/1.0.0-rc2
