### ISSUE TITLE
Transforming Property Names Issue

### ISSUE THREAD

**Issue by richardcroprecords** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#98]
When I transform property names the context still refers to the untransformed property.

            services.AddHandlebarsTransformers(
                entityNameTransformer: n => n + "Foo",
                entityFileNameTransformer: n => n + "Foo",
                constructorTransformer: e => new EntityPropertyInfo(e.PropertyType, e.PropertyName + "Foo"),
                propertyTransformer: e => new EntityPropertyInfo(e.PropertyType, e.PropertyName + "Foo"),
                navPropertyTransformer: e => new EntityPropertyInfo(e.PropertyType, e.PropertyName + "Foo"));

In the generated class:

        public long? DeletedFoo { get; set; }

In the generated context:

                entity.Property(e => e.Deleted)
                    .HasColumnName("deleted")
                    .HasDefaultValueSql("0");

**Comment by codingdna2** [comment]
I guess PR #102 address this?

I add that it would be nice not to have to include all the parameters (if I transform only entityName, constructor and navProperties should be generated accordingly).

**Comment by birtej** [comment]
I'm not sure if this covers it, but transformed entity names are also not being used in generated constraints

**Comment by tonysneed** [comment]
Closed by #118
